# [Configuration file] Climate-invariant - Specific humidity - Minus 4K - Training and validation
exp_name: 000_example
data_dir: /local/Tom.Beucler/SPCAM_PHYS/
train_fn: CI_SP_M4K_train_shuffle.nc
valid_fn: CI_SP_M4K_valid.nc
norm_fn: CI_SP_M4K_NORM_norm.nc

inputs: [QBP,TBP,PS,SOLIN,SHFLX,LHFLX]
outputs: [PHQ,TPHYSTND,FSNT,FSNS,FLNT,FLNS]

input_sub: mean
input_div: maxrs
output_dict: /home/t/Tom.Beucler/SPCAM/CBRAIN-CAM/nn_config/scale_dicts/009_Wm2_scaling.pkl

hidden_layers: [1, 1]
epochs: 1
conservation_layer: False
loss: mse