# Define input and output variables
# Important: Do not include quatation marks!
vars: [TAP, QAP, SHFLX, LHFLX, LAT, dTdt_adiabatic, dQdt_adiabatic, QRL, QRS, SPDT, SPDQ, PS, PRECT, FLUT, SOLIN]   # All variables, feature and target
current_vars: [SPDT, SPDQ, QRL, QRS, PRECT, FLUT]          # Variables to take from current time step