# Define input and output variables
# Important: Do not include quatation marks!
in_vars: [TAP, QAP, OMEGA, SHFLX, LHFLX, LAT, dTdt_adiabatic, dQdt_adiabatic, QRL, QRS]   # Inputs/features
out_vars: [SPDT, SPDQ]          # Outputs/targets