# Define input and output variables
# Important: Do not include quatation marks!
vars: [TAP, QAP, OMEGA, SHFLX, LHFLX, LAT, dTdt_adiabatic, dQdt_adiabatic, QRL, QRS, SPDT, SPDQ, PS, PRECT, FLUT, SPDQC, SPDQI]   # All variables, feature and target
current_vars: [SPDT, SPDQ, OMEGA, QRL, QRS, PRECT, FLUT, SPDQC, SPDQI]          # Variables to take from current time step